# https://github.com/OpenNewsLabs/autoEdit_2/issues/36

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      sudo: required
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
        - TRAVIS_TAG="1.0.12"
        - UPLOADTOOL_SUFFIX=autoEdit2
    - os: linux
      dist: trusty
      sudo: required
      services: docker
      language: node_js
      node_js: "10"
      env:
        - TRAVIS_TAG="1.0.12"
        - UPLOADTOOL_SUFFIX=autoEdit2
      addons:
        apt:
          packages:
            - libgnome-keyring-dev
            - icnsutils
cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.npm
  - $HOME/.nvm

env:
  global:
    - TRAVIS_TAG="1.0.12"
    - UPLOADTOOL_SUFFIX="autoEdit2"

install:
  - node --version
  - npm --version
  - npm install

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    npm run build:linux;
    find . | grep AppImage;
    bash upload.sh ./dist/autoEdit2-*-x86_64.AppImage; 
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    npm run build:mac;
    find . | grep dmg;
    bash upload.sh ./dist/autoEdit2-*.dmg; 
    fi
    # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run build:linux; fi
    # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then  find . | grep AppImage; fi
    # - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then bash upload.sh ./dist/autoEdit2-*-x86_64.AppImage; fi
    # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run build:mac; fi
    # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then find . | grep dmg; fi
    # - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then bash upload.sh ./dist/autoEdit2-*.dmg; fi


branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/