# https://github.com/OpenNewsLabs/autoEdit_2/issues/36

language: node_js
node_js:
  - "10"

os: osx
osx_image: xcode9.4
sudo: required

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.npm
  - $HOME/.nvm

# addons:
#   apt:
#     packages:
#       - libgnome-keyring-dev
#       - icnsutils

env:
  global:
    - TRAVIS_TAG="1.0.12"
    - UPLOADTOOL_SUFFIX="autoEdit2"

install:
  - node --version
  - npm --version
  - npm install

script:
#  - npm run test
# - npm run build
  - npm run build:mac
  - find . | grep dmg
  # - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./dist/autoEdit2-*.dmg; 

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/