# https://github.com/OpenNewsLabs/autoEdit_2/issues/36

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "10"
      env:
        - ELECTRON_CACHE=$HOME/.cache/electron
        - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

    - os: linux
      services: docker
      language: generic
env:
  global:
    - TRAVIS_TAG="1.0.12"
    - UPLOADTOOL_SUFFIX=autoEdit2

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.npm
  - $HOME/.nvm

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

install:
  - node --version
  - npm --version
  - npm install

script:
#  - npm run test
# - npm run build
  - npm run build:linux
  - find . | grep AppImage
# - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./dist/autoEdit2-*-x86_64.AppImage

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/