# https://github.com/OpenNewsLabs/autoEdit_2/issues/36

language: node_js
node_js:
  - "7"

os: 
  - linux
  - osx

dist: trusty
osx_image: xcode9.4
sudo: required

# cache:
#   directories:
#   - node_modules
#   - $HOME/.electron
#   - $HOME/.npm
#   - $HOME/.nvm

env:
  global:
    - TRAVIS_TAG="1.0.12"
    - UPLOADTOOL_SUFFIX="autoEdit2"

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

install:
  - node --version
  - npm --version
  - npm install


script:
# - npm run test
# - npm run build
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    echo "INSIDE Travis OS Linux script";
    npm run build:linux;
    find . | grep AppImage;
    # - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    bash upload.sh ./dist/autoEdit2-*-x86_64.AppImage;
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    npm run build:mac;
    ls ./dist;
    find . | grep mac.zip;
    #wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    bash upload.sh ./dist/autoEdit2-*-mac.zip; 
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/