# https://github.com/OpenNewsLabs/autoEdit_2/issues/36

language: node_js
node_js:
  - "7"

os: osx
osx_image: xcode9.3
sudo: required

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.npm
  - $HOME/.nvm

install:
  - node --version
  - npm --version
  - npm install

script:
#  - npm run test
  - npm run build
  - find . | grep dmg
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh ./dist/autoEdit2-*-mac.zip

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/