# https://github.com/OpenNewsLabs/autoEdit_2/issues/36

language: node_js
node_js:
  - "10"

os: 
  - osx
  - linux
osx_image: xcode9.4
sudo: required

dist: trusty

cache:
  directories:
  - node_modules
  - $HOME/.electron
  - $HOME/.npm
  - $HOME/.nvm

addons:
  apt:
    packages:
      - libgnome-keyring-dev
      - icnsutils

env:
  global:
    - TRAVIS_TAG="1.0.12"
    - UPLOADTOOL_SUFFIX="autoEdit2"

install:
  - node --version
  - npm --version
  - npm install

script:
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    npm run build:linux;
    ls ./dist;
    find . | grep AppImage;
    #wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    bash upload.sh ./dist/autoEdit2-*-x86_64.AppImage; 
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    npm run build:mac;
    ls ./dist;
    find . | grep mac.zip;
    #wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    bash upload.sh ./dist/autoEdit2-*-mac.zip; 
    fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/