# https://github.com/OpenNewsLabs/autoEdit_2/issues/36
matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      language: node_js
      node_js: "7"
      sudo: required
    - os: linux
      language: node_js
      node_js: "7"
      sudo: required
      # services: docker
      addons:
        apt:
          packages:
            - libgnome-keyring-dev
            - icnsutils

# cache:
#   directories:
#   - node_modules
#   - $HOME/.electron
#   - $HOME/.npm
#   - $HOME/.nvm

env:
  global:
    # - TRAVIS_TAG="1.0.12"
    - UPLOADTOOL_SUFFIX="autoEdit2"
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder

install:
  - node --version
  - npm --version
  - npm install
  - npm run make_js

# reading version number from json using bash and assigning to enviroment variable for travis as explained ehre https://gist.github.com/DarrenN/8c6a5b969481725a4413

script:
  - TRAVIS_TAG=$(cat ./package.json | grep version | head -1 | awk -F: '{ print $2 }' | sed 's/[",]//g')
  - |
    if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    echo "INSIDE Travis OS Linux script";
    npm run build:linux;
    find . | grep AppImage;
    # - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    bash upload.sh ./dist/autoEdit2-*-x86_64.AppImage;
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    npm run build:mac;
    ls ./dist;
    find . | grep mac.zip;
    #wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
    bash upload.sh ./dist/autoEdit2-*-mac.zip; 
    fi
  # - |
  #   if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
  #   docker run --rm \
  #   --env-file <(env | grep -iE 'DEBUG|NODE_|ELECTRON_|YARN_|NPM_|CI|CIRCLE|TRAVIS|APPVEYOR_|CSC_|_TOKEN|_KEY|AWS_|STRIP|BUILD_') \
  #   -v ${PWD}:/project \
  #   -v ~/.cache/electron:/root/.cache/electron \
  #   -v ~/.cache/electron-builder:/root/.cache/electron-builder \
  #   electronuserland/builder:wine \
  #   /bin/bash -c "npm run build --win"\
  #   /bin/bash -c "echo 'in windows command'"\
  #   # /bin/bash -c "wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh"\
  #   /bin/bash -c "upload.sh ./dist/autoEdit2-*.exe.zip";
  #   fi

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous)/